ModuloInventarioWeb/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ModuloInventarioWeb.Data;
using ModuloInventarioWeb.Models;

namespace ModuloInventarioWeb.Controllers;

    public class CategoriaController : Controller
    {
        private readonly ICategoriaData _data;

        public CategoriaController(ICategoriaData data)
        {
            _data = data;
        }

        public async Task<IActionResult> Index(int pg = 1)
        {
            try
            {
                IEnumerable<Categoria> objCategoriaList = await _data.GetCategoria();
                const int pageSize = 9;

                if (pg < 1) pg = 1;

                int recsCount = objCategoriaList.Count();
                var pager = new Pager(recsCount, pg, pageSize);
                int recSkip = (pg - 1) * pageSize;
                var data = objCategoriaList.Skip(recSkip).Take(pager.PageSize);

                ViewBag.Pager = pager;

            return View(data);
            }
            catch (Exception ex)
            {
                return NotFound(ex.Message);
            }
        }
        public  IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Categoria categoria)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _data.InsertCategoria(categoria);
                    TempData["success"] = "Categoría creada exitosamente";
                    return RedirectToAction("Index");
                }

                return View(categoria);
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(categoria);
            }
        }

    public async Task<IActionResult> Edit(int? id)
    {

        if (id is 0 or null)
        {
            return NotFound();
        }

        try
        {
            var obj = await _data.GetCategoria((int)id);

            if (obj is null)
                return NotFound();

            return View(obj);
        }
        catch (Exception ex)
        {
            return NotFound(ex.Message);
        }
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Categoria categoria)
    {
        try
        {
            await _data.UpdateCategoria(categoria);
            TempData["success"] = "Categoría actualizada exitosamente";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
            return View(categoria);
        }
    }

    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await _data.DeleteCategoria(id);
            TempData["success"] = "Categoría eliminada exitosamente";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
            return RedirectToAction("Index");
        }
    }

}

ModuloInventarioWeb/Controllers/KardexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModuloInventarioWeb.Data;
using ModuloInventarioWeb.Models;

namespace ModuloInventarioWeb.Controllers
{
    [Authorize]
    public class KardexController : Controller
    {

        private readonly IKardexData _kardexData;
        private readonly IProductoData _productoData;
        private readonly IUsuarioData _usuarioData;

        public KardexController(IKardexData kardexData, IProductoData productoData, IUsuarioData usuarioData)
        {
            _kardexData = kardexData;
            _productoData = productoData;
            _usuarioData = usuarioData;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                List<SelectListItem> listaProductos = ObtenerListaProductos().Result;
                ViewBag.ListaProductos = listaProductos;

                return View();
            }
            catch (Exception ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Index(Kardex kardex)
        {
            try
            {
                int IdProducto = kardex.IdProducto;
                IEnumerable<Kardex> kardices = await _kardexData.GetByProducto(IdProducto);

                Producto producto = await _productoData.GetProducto(IdProducto);
                ViewBag.Producto = producto;

                List<SelectListItem> listaProductos = ObtenerListaProductos().Result;
                ViewBag.ListaProductos = listaProductos;

                foreach (Kardex kardexp in kardices)
                {
                    kardexp.Usuario = await _usuarioData.GetUsuario(kardex.IdUsuario);
                    kardexp.Producto = await _productoData.GetProducto(kardex.IdProducto);
                }

                return View(kardices);
            }
            catch (Exception ex)
            {
                return NotFound(ex.Message);
            }
        }

        private async Task<List<SelectListItem>> ObtenerListaProductos()
        {
            IEnumerable<Producto> listaProductos = await _productoData.GetProducto();
            List<SelectListItem> listItems = new List<SelectListItem>();

            foreach (var producto in listaProductos)
            {
                listItems.Add(new SelectListItem
                {
                    Text = producto.Nombre,
                    Value = producto.ID_Producto.ToString()
                });
            }
            return listItems;
        }
    }
}

ModuloInventarioWeb/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModuloInventarioWeb.Data;
using ModuloInventarioWeb.Models;
using static System.Net.Mime.MediaTypeNames;

namespace ModuloInventarioWeb.Controllers;

[Authorize]
public class ProductoController : Controller
{
    private readonly IProductoData _data;
    private readonly ICategoriaData _categoriaData;

    public ProductoController(IProductoData data, ICategoriaData categoriaData)
    {
        _data = data;
        _categoriaData = categoriaData;
    }

    public async Task<IActionResult> Index(int pg = 1)
    {
        try
        {
            IEnumerable<Producto> objProductoList = await _data.GetProducto();
            const int pageSize = 5;

            if (pg < 1) pg = 1;

            int recsCount = objProductoList.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = objProductoList.Skip(recSkip).Take(pager.PageSize);

            ViewBag.Pager = pager;

            return View(data);
        }
        catch (Exception ex)
        {
            return NotFound(ex.Message);
        }
    }

    public  IActionResult Create()
    {
        try
        {
            List<SelectListItem> lista = ObtenerCategorias().Result;
            ViewBag.ListaCategorias = lista;
        }
        catch (Exception ex){ 
        }
        return View();
    }

    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Producto producto)
    {
        try
        {
            List<SelectListItem> lista = ObtenerCategorias().Result;
            ViewBag.ListaCategorias = lista;
            IFormFile imagen = Request.Form.Files[0];
            var filestream = imagen.OpenReadStream();
            byte[] data = new byte[filestream.Length];
            filestream.Read(data, 0, data.Length);

           

            if (ModelState.IsValid)
            {
                producto.Imagen_Producto = data;
                await _data.InsertProducto(producto);
                TempData["success"] = "Producto creado exitosamente";
                return RedirectToAction("Index");
            }

            return View(producto);
        }
        catch (Exception ex)
        {
          
            TempData["error"] = ex.Message;
            return View(producto);
        }
    }

    public async Task<IActionResult> Edit(int? id)
    {
        List<SelectListItem> lista = ObtenerCategorias().Result;
        ViewBag.ListaCategorias = lista;

        if (id is 0 or null)
        {
            return NotFound();
        }

        try
        {
            var obj = await _data.GetProducto((int)id);

            if (obj is null)
                return NotFound();

            return View(obj);
        }
        catch (Exception ex)
        {
            return NotFound(ex.Message);
        }
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Producto producto)
    {
        try
        {
            if (Request.Form.Files.Count() > 0)
            {
                IFormFile imagen = Request.Form.Files[0];
                var filestream = imagen.OpenReadStream();
                byte[] data = new byte[filestream.Length];
                filestream.Read(data, 0, data.Length);
                producto.Imagen_Producto = data;
            } else
            {
                var obj = await _data.GetProducto(producto.ID_Producto);
                producto.Imagen_Producto = obj.Imagen_Producto;
            }

            await _data.UpdateProducto(producto);
            TempData["success"] = "Producto actualizado exitosamente";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            List<SelectListItem> lista = ObtenerCategorias().Result;
            ViewBag.ListaCategorias = lista;
            TempData["error"] = ex.Message;
            return View(producto);
        }
    }

    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await _data.DeleteProducto(id);
            TempData["success"] = "Producto eliminada exitosamente";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
            return RedirectToAction("Index");
        }
    }



    private async Task<List<SelectListItem>> ObtenerCategorias()
    {
        IEnumerable<Categoria> listaCategorias = await _categoriaData.GetCategoria();
        List<SelectListItem> listItems = new List<SelectListItem>();

        foreach (var categoria in listaCategorias)
        {
            listItems.Add(new SelectListItem
            {
                Text = categoria.Nombre,
                Value = categoria.ID_Categoria.ToString()
            });
        }
        return listItems;
    }

    public async Task<IActionResult> View(int? id)
    {
        List<SelectListItem> lista = ObtenerCategorias().Result;
        ViewBag.ListaCategorias = lista;

        if (id is 0 or null)
        {
            return NotFound();
        }

        try
        {
            var obj = await _data.GetProducto((int)id);

            if (obj is null)
                return NotFound();

            return View(obj);
        }
        catch (Exception ex)
        {
            return NotFound(ex.Message);
        }
    }


}

ModuloInventarioWeb/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ModuloInventarioWeb.Data;
using ModuloInventarioWeb.Helpers;
using ModuloInventarioWeb.Models;
using static System.Net.Mime.MediaTypeNames;
namespace ModuloInventarioWeb.Controllers;

[Authorize]
public class UsuarioController : Controller
{
    private readonly IUsuarioData _data;

    public UsuarioController(IUsuarioData data)
    {
        _data = data;
    }

    public async Task<IActionResult> Index(int pg = 1)
    {
        try
        {
            IEnumerable<Usuario> objUsuarioList = await _data.GetUsuario();

            const int pageSize = 5;

            if (pg < 1) pg = 1;

            int recsCount = objUsuarioList.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = objUsuarioList.Skip(recSkip).Take(pager.PageSize);

            ViewBag.Pager = pager;
            return View(data);
        }
        catch (Exception ex)
        {
            return NotFound(ex.Message);
        }
    }
    public IActionResult Create()
    {
        return View();
    }

    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Usuario usuario, String password)
    {
        try
        {
            IFormFile imagen = Request.Form.Files[0];
            var filestream = imagen.OpenReadStream();
            byte[] data = new byte[filestream.Length];
            filestream.Read(data, 0, data.Length);

            string salt = usuario.Nombre.ToUpper();
            byte[] passTemporal = HelperCryptography.EncriptarPassword(password, salt);

            if (ModelState.IsValid)
            {
                usuario.Foto_Perfil = data;
                usuario.Contrasena = passTemporal;
                await _data.InsertUsuario(usuario);
                TempData["success"] = "Usuario creado exitosamente";
                return RedirectToAction("Index");
            }

            return View(usuario);
        }
        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
            return View(usuario);
        }
    }

    public async Task<IActionResult> Edit(int? id)
    {

        if (id is 0 or null)
        {
            return NotFound();
        }

        try
        {
           
            var obj = await _data.GetUsuario((int)id);

            if (obj is null)
                return NotFound();

            return View(obj);
        }
        catch (Exception ex)
        {
            return NotFound(ex.Message);
        }
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Usuario usuario, string password)
    {
        try
        {
            if (Request.Form.Files.Count() > 0)
            {
                IFormFile imagen = Request.Form.Files[0];
                var filestream = imagen.OpenReadStream();
                byte[] data = new byte[filestream.Length];
                filestream.Read(data, 0, data.Length);
                usuario.Foto_Perfil = data;
            } else
            {
                var obj = await _data.GetUsuario(usuario.ID_Usuario);
                usuario.Foto_Perfil = obj.Foto_Perfil;
            }

            string salt = usuario.Nombre.ToUpper();
            byte[] passTemporal = HelperCryptography.EncriptarPassword(password, salt);

            usuario.Contrasena = passTemporal;

            await _data.UpdateUsuario(usuario);

            TempData["success"] = "Usuario actualizado exitosamente";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
            return View(usuario);
        }
    }

    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await _data.DeleteUsuario(id);
            TempData["success"] = "Usuario eliminado exitosamente";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
            return RedirectToAction("Index");
        }
    }
}

ModuloInventarioWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Modulo Inventario</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ModuloInventarioWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Modulo Inventario</a>
                <button class="btn open" type="button" data-bs-toggle="collapse" data-bs-target=".sidebar" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon open"></span>
                </button>
                <div class="sidebar collapse justify-content-end">
                    <button class="btn close" type="button">
                        <span class="bi bi-x-lg close"></span>
                    </button>
                    <ul class="navbar-nav d-flex flex-column">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-door"></i> Inicio</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Requerimiento" asp-action="Index"><i class="bi bi-postcard"></i> Requerimientos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Movimiento" asp-action="Index"><i class="bi bi-card-checklist"></i> Movimientos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Kardex" asp-action="Index"><i class="bi bi-journal-text"></i> Kardex</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index"><i class="bi bi-box-seam"></i> Producto</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index"><i class="bi bi-tag"></i> Categoria</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index"><i class="bi bi-person"></i> Usuario</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Autenticacion" asp-action="Salir"><i class="bi bi-box-arrow-right"></i> Salir</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ModuloInventarioWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    <script>
        document.addEventListener('click', (e) => {
            if ($(e.target).hasClass("close") || !$(e.target).hasClass("sidebar")) {
                e.stopPropagation();
                $("body").css("overflow", "");
                $(".sidebar").removeClass("show");
            }

            if ($(e.target).hasClass("open")) {
                e.stopPropagation();
                $("body").css("overflow", "hidden");
                $(".sidebar").removeClass("show");
            }
        });
    </script>
</body>
</html>

ModuloInventarioWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }

        toastr.success('@TempData["success"]', 'System Says');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }

        toastr.error('@TempData["error"]', 'System Says');
    </script>
}